weather:
  api-key: ${WEATHER_APIKEY:}

  host: http://api.openweathermap.org
  port: ~
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect